spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/xj_ykt
    username: root
    password: 123456
    
novellist:
  list[0]:
     name: sql1
     type: 2
     master: 3
     author: 4
     description: 5
  list[1]:
     name: sql2
     type: 7
     master: 8
     author: 9
     description: 9
  list[2]:   
     name: sql3
     type: 11
     master: 12
     author: 13
     description: 14
